### ISSUE TITLE
docker compose pull image onprem

### ISSUE THREAD

**Issue by mfamw** [taskforcesh/issues#181]
Having trouble pulling the image.  Says not authorized.  using this:

```
services:
  backend:
    image: docker.taskforce.sh/onprem/dashboard:1.6.0
    restart: always
    ports:
      - "9876:9876"
    environment:
      REGISTRY_USER: ${DOCKER_USER}
      REGISTRY_PASSWORD: ${DOCKER_PASS}
      LICENSE_KEY: ${LICENSE_KEY}
```
